name: Compile and deploy LaTeX document

on: [push, pull_request]

jobs:
  compile_document:
    runs-on: ubuntu-latest
    name: Compile document
    steps:
    - uses: actions/checkout@v2
    - name: Build PDFs with the LaTeX engine in Docker
      uses: ftsrg/document-converter-actions@master
      with:
        # run Makefile target `test` from the `src` LaTeX source folder
        makefile-arguments: -C src test
    - name: Compile deploy package
      run: |
        OUT_DIR=out/
        mkdir -p $OUT_DIR
        {
          echo '- [`[XeLaTeX HU]`](thesis-xelatex-hu.pdf) | [`[PDFLaTeX HU]`](thesis-pdflatex-hu.pdf) | [`[LuaLaTeX HU]`](thesis-lualatex-hu.pdf)'
          echo '- [`[XeLaTeX EN]`](thesis-xelatex-en.pdf) | [`[PDFLaTeX EN]`](thesis-pdflatex-en.pdf) | [`[LuaLaTeX EN]`](thesis-lualatex-en.pdf)'
          echo '- [`[XeLaTeX Duplex]`](thesis-xelatex-duplex.pdf) | [`[PDFLaTeX Duplex]`](thesis-pdflatex-duplex.pdf) | [`[LuaLaTeX Duplex]`](thesis-lualatex-duplex.pdf)'
          echo "- Commit: [$GITHUB_SHA](https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA)"
        } > $OUT_DIR/README.md
        # copy PDF outputs from `pdf` folder
        cp pdf/*.pdf $OUT_DIR
    - name: Deploy site and PDFs
      uses: JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92  # 4.1.4
      with:
        branch: gh-pages
        folder: out
        single-commit: true
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
